export const shippingInvoices = [
    {
      consigneeName: "Global Traders Ltd.",
      containerId: "C123456789",
      origin: "Shanghai, China",
      destination: "New York, USA",
      invoiceNo: "INV-1001",
      totalUsd: 12500,
      totalEud: 11700,
    },
    {
      consigneeName: "Eastern Imports Co.",
      containerId: "C987654321",
      origin: "Tokyo, Japan",
      destination: "Hamburg, Germany",
      invoiceNo: "INV-1002",
      totalUsd: 8900,
      totalEud: 8300,
    },
    {
      consigneeName: "Mediterranean Goods Inc.",
      containerId: "C123789456",
      origin: "Athens, Greece",
      destination: "Buenos Aires, Argentina",
      invoiceNo: "INV-1003",
      totalUsd: 13700,
      totalEud: 12850,
    },
    {
      consigneeName: "Atlantic Cargo Services",
      containerId: "C456123789",
      origin: "Cape Town, South Africa",
      destination: "London, UK",
      invoiceNo: "INV-1004",
      totalUsd: 15600,
      totalEud: 14600,
    },
    {
      consigneeName: "North Sea Logistics",
      containerId: "C789456123",
      origin: "Rotterdam, Netherlands",
      destination: "Miami, USA",
      invoiceNo: "INV-1005",
      totalUsd: 17450,
      totalEud: 16200,
    },
    {
      consigneeName: "Southern Exports Ltd.",
      containerId: "C654321987",
      origin: "Sydney, Australia",
      destination: "Singapore",
      invoiceNo: "INV-1006",
      totalUsd: 9500,
      totalEud: 8800,
    },
    {
      consigneeName: "Pacific Rim Co.",
      containerId: "C321654987",
      origin: "Los Angeles, USA",
      destination: "Hong Kong",
      invoiceNo: "INV-1007",
      totalUsd: 10300,
      totalEud: 9600,
    },
    {
      consigneeName: "Baltic Freight Forwarders",
      containerId: "C159753456",
      origin: "Riga, Latvia",
      destination: "Oslo, Norway",
      invoiceNo: "INV-1008",
      totalUsd: 12100,
      totalEud: 11300,
    },
  ];
