export const dummyItemsData = [
  {
    delivery: "Kigali, Rwanda",
    shipper: "ABC Logistics",
    consignee: "XYZ Retailers",
    phoneNumber: "+250781234567",
    code: "RW20240918A1",
    mark: "KG001",
    salesAgent: "John Doe",
    noOfPkgs: 10,
    typeOfPkgs: "Boxes",
    weight: "200kg",
    line: "Air",
    handling: "Standard",
    type: "Perishable",
    cbm: "2.5",
    description: "Fresh produce",
    freight: "500 USD",
    blFee: "50 USD",
    jb: "N/A",
    others: "20 USD",
    totalUSD: "570 USD",
    totalAED: "2093 AED",
    invoiceNo: "INV2024091801",
  },
  {
    delivery: "Goma, DRC",
    shipper: "Logistics Pro",
    consignee: "Global Enterprises",
    phoneNumber: "+243991234567",
    code: "RW20240918B2",
    mark: "GM002",
    salesAgent: "Jane Smith",
    noOfPkgs: 5,
    typeOfPkgs: "Pallets",
    weight: "500kg",
    line: "Road",
    handling: "Express",
    type: "Non-perishable",
    cbm: "3.0",
    description: "Building materials",
    freight: "800 USD",
    blFee: "70 USD",
    jb: "30 USD",
    others: "15 USD",
    totalUSD: "915 USD",
    totalAED: "3360 AED",
    invoiceNo: "INV2024091802",
  },
  {
    delivery: "Butare, Rwanda",
    shipper: "Fast Shippers",
    consignee: "Agrico Ltd",
    phoneNumber: "+250785678901",
    code: "RW20240918C3",
    mark: "BT003",
    salesAgent: "Paul Nkurunziza",
    noOfPkgs: 20,
    typeOfPkgs: "Crates",
    weight: "150kg",
    line: "Air",
    handling: "Standard",
    type: "Fragile",
    cbm: "1.8",
    description: "Glassware",
    freight: "600 USD",
    blFee: "40 USD",
    jb: "N/A",
    others: "10 USD",
    totalUSD: "650 USD",
    totalAED: "2386 AED",
    invoiceNo: "INV2024091803",
  },
  {
    delivery: "Bukavu, DRC",
    shipper: "TranspoMax",
    consignee: "Bukavu Traders",
    phoneNumber: "+243977654321",
    code: "RW20240918D4",
    mark: "BK004",
    salesAgent: "Alice Kayonga",
    noOfPkgs: 12,
    typeOfPkgs: "Containers",
    weight: "600kg",
    line: "Sea",
    handling: "Heavy-duty",
    type: "Non-perishable",
    cbm: "5.0",
    description: "Machinery parts",
    freight: "1000 USD",
    blFee: "100 USD",
    jb: "50 USD",
    others: "30 USD",
    totalUSD: "1180 USD",
    totalAED: "4329 AED",
    invoiceNo: "INV2024091804",
  },
  {
    delivery: "Musanze, Rwanda",
    shipper: "Cargo Express",
    consignee: "Farmers Co-op",
    phoneNumber: "+250788654321",
    code: "RW20240918E5",
    mark: "MS005",
    salesAgent: "David Mugisha",
    noOfPkgs: 8,
    typeOfPkgs: "Sacks",
    weight: "100kg",
    line: "Road",
    handling: "Standard",
    type: "Perishable",
    cbm: "1.2",
    description: "Grains",
    freight: "200 USD",
    blFee: "30 USD",
    jb: "N/A",
    others: "5 USD",
    totalUSD: "235 USD",
    totalAED: "862 AED",
    invoiceNo: "INV2024091805",
  },
];
