-- AlterTable
ALTER TABLE "CalculationDependancy" ALTER COLUMN "fullTransportFee" SET DEFAULT 0,
ALTER COLUMN "fullTransportFee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "groupageTransportFee" SET DEFAULT 4800,
ALTER COLUMN "groupageTransportFee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fullContSeaFee" SET DEFAULT 4700,
ALTER COLUMN "fullContSeaFee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "groupageSeaFee" SET DEFAULT 4700,
ALTER COLUMN "groupageSeaFee" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Commissions" ALTER COLUMN "rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "amountPaid" SET DEFAULT 0,
ALTER COLUMN "amountPaid" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "vat" SET DEFAULT 0,
ALTER COLUMN "vat" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "amountPaid" SET DEFAULT 0,
ALTER COLUMN "amountPaid" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "stuffingreportItems" ALTER COLUMN "line" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "handling" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "freight" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "blFee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "jb" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalAed" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalUsd" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "carHanging" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "inspection" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "insurance" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "recovery" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "localCharges" SET DATA TYPE DOUBLE PRECISION;
