export const headers = [
    { header: "Delivery", field: "delivery" },
    { header: "Shipper", field: "shipper" },
    { header: "Consignee", field: "consignee" },
    { header: "Phone Number", field: "phoneNumber" },
    { header: "Code", field: "code" },
    { header: "Mark", field: "mark" },
    { header: "Sales Agent", field: "salesAgent" },
    { header: "No of Pkgs", field: "noOfPkgs" },
    { header: "Type of Pkgs", field: "typeOfPkgs" },
    { header: "Wgt", field: "weight" },
    { header: "Line", field: "line" },
    { header: "Handling", field: "handling" },
    { header: "Type", field: "type" },
    { header: "CBM", field: "cbm" },
    { header: "Description", field: "description" },
    { header: "Freight", field: "freight" },
    { header: "BL Fee", field: "blFee" },
    { header: "JB", field: "jb" },
    { header: "Others", field: "others" },
    { header: "Total $", field: "totalUSD" },
    { header: "Total AED", field: "totalAED" },
    { header: "Invoice No.", field: "invoiceNo" }
  ];
