export const headers = [
  { header: "Shipper", field: "shipperId" },
  { header: "Consignee", field: "consigneeId" },
  { header: "Phone Number", field: "phone" },
  { header: "Code", field: "code" },
  { header: "Mark", field: "mark" },
  { header: "Sales Agent", field: "salesAgent" },
  { header: "No of Pkgs", field: "noOfPkgs" },
  { header: "Type of Pkgs", field: "typeOfPkg" },
  { header: "Wgt", field: "weight" },
  { header: "Line", field: "line" },
  { header: "Handling", field: "handling" },
  { header: "Type", field: "type" },
  { header: "CBM", field: "cbm" },
  { header: "Description", field: "description" },
  { header: "Freight", field: "freight" },
  { header: "BL Fee", field: "blFee" },
  { header: "JB", field: "jb" },
  { header: "Others", field: "others" },
  { header: "Total $", field: "totalUsd" },
  { header: "Total AED", field: "totalAed" },
  { header: "Invoice No.", field: "invoiceNo" },
];
